import type { NextPage } from "next";
import Head from "next/head";
import React, { useEffect, useState } from "react";

import { LinhaLivro } from "../../componentes/LinhaLivro";
import { Menu } from "../../componentes/Menu";
import styles from "../styles/Home.module.css";
import { ControleLivros, LivroMongo } from "../../classes/controle/ControleLivros";


const LivroLista: NextPage = () => {
  const [carregado, setCarregado] = useState(false);
  const [livros, setLivros] = useState<Array<LivroMongo>>([]);
  

  useEffect(() => {
    const controleLivros: ControleLivros = new ControleLivros();
    controleLivros.obterLivros().then((data) => {
      setLivros(data);
      setCarregado(true);
    });
  }, [carregado]);

  const excluir = (codigo: String) => {
    const controleLivros: ControleLivros = new ControleLivros();
    controleLivros.excluir(codigo).then(() => {
      setCarregado(false);
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Loja Next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu></Menu>
      <main className="estilo-dados">
        <h1>Catálogo de Livro</h1>
        <table className=" table table-striped table-bordered table-hover">
        <thead className="table-dark">
          <tr>
            <th>titulo</th>
            <th>resumo</th>
            <th>editora</th>
            <th>autores</th>
          </tr>
        </thead>
          <tbody>
          {livros &&
            livros.map((livro, index) => {
              return (
                <LinhaLivro
                  key={index}
                  excluir={() => {
                    excluir(livro._id!);
                  }}
                  livro={livro}
                ></LinhaLivro>
              );
            })}
          </tbody>
        </table>
      </main>
    </div>
  );
};

export default LivroLista;
